//
//  ColorListRouter.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorListRoutingLogic {
    func routeToColorScene(id: ColorID)
}

protocol ColorListDataPassing: class {
    var dataStore: ColorListDataStore? { get }
}

class ColorListRouter: ColorListDataPassing {
    weak var viewController: ColorListViewController?
    var dataStore: ColorListDataStore?
}

// MARK: - ColorListRoutingLogic
extension ColorListRouter: ColorListRoutingLogic {
    
    func routeToColorScene(id: ColorID) {
        let vc = ColorSceneBuilder.build(colorID: id)
        viewController?.show(vc, sender: nil)
    }

}
