//
//  ColorListBuilder.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorListBuilder {
    
    static func build() -> ColorListViewController {
        let viewController = configureModule()
        viewController.title = "Colors"
        return viewController
    }
    
    private static func configureModule() -> ColorListViewController {
        let viewController = ColorListViewController()
        let interactor = ColorListInteractor()
        let presenter = ColorListPresenter()
        let router = ColorListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        return viewController
    }
    
}
