//
//  ColorListPresenter.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorListPresentationLogic: class {
    func presentFetchingResult(response: ColorList.Fetching.Response)
    func presentLoadingStart(response: ColorList.StartLoading.Response)
    func presentLoadingStop(response: ColorList.StopLoading.Response)
}

class ColorListPresenter: ColorListPresentationLogic {
    weak var viewController: ColorListDisplayLogic?
    
    // MARK: - ColorListPresentationLogic
    
    func presentFetchingResult(response: ColorList.Fetching.Response) {
        let displayedColors = response.colors.compactMap { ColorList.DisplayedColors(id: $0.id,
                                                                                     color: UIColor(hex: $0.hex),
                                                                                     name: $0.name) }
        let viewModel = ColorList.Fetching.ViewModel(displayedColors: displayedColors)
        viewController?.displayFetchingResult(viewModel: viewModel)
    }
    
    func presentLoadingStart(response: ColorList.StartLoading.Response) {
        viewController?.displayLoadingStart(viewModel: ColorList.StartLoading.ViewModel())
    }
    
    func presentLoadingStop(response: ColorList.StopLoading.Response) {
        viewController?.displayLoadingStop(viewModel: ColorList.StopLoading.ViewModel())
    }
    
    // MARK: - Private methods
}
