//
//  ColorListWorker.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ColorListWorker {
    
    func fetchData(completion: @escaping (Result<[Color], Error>) -> Void) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            let colors = LocalDB.shared.getColors()
            completion(.success(colors))
        }
    }

}
