//
//  ColorListModels.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorList {
    
    struct DisplayedColors {
        var id: ColorID
        var color: UIColor?
        var name: String
    }
    
    // MARK: Use cases
    
    enum Fetching {
        struct Request {
        }
        struct Response {
            var colors: [Color]
        }
        struct ViewModel {
            var displayedColors: [DisplayedColors]
        }
    }
    
    enum StartLoading {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum StopLoading {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
