//
//  ColorScenePresenter.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorScenePresentationLogic: class {
    func presentFetchingResult(response: ColorScene.Fetching.Response)
}

class ColorScenePresenter: ColorScenePresentationLogic {
    weak var viewController: ColorSceneDisplayLogic?
    
    // MARK: - ColorScenePresentationLogic
    
    func presentFetchingResult(response: ColorScene.Fetching.Response) {
        let displayedColor = ColorScene.DisplayedColor(title: response.color?.name ?? "Black",
                                                       color: UIColor(hex: response.color?.hex ?? "#000000"))
        let viewModel = ColorScene.Fetching.ViewModel(displayedColor: displayedColor)
        viewController?.displayFetchingResult(viewModel: viewModel)
    }
    
    // MARK: - Private methods
}
