//
//  ColorSceneInteractor.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorSceneBusinessLogic {
    func fetchData(request: ColorScene.Fetching.Request)
}

protocol ColorSceneDataStore: class {

}

class ColorSceneInteractor: ColorSceneDataStore {
    var presenter: ColorScenePresentationLogic?
    private let worker = ColorSceneWorker()

    private var colorID: ColorID
    init(colorID: ColorID) {
        self.colorID = colorID
    }
}

// MARK: - ColorSceneBusinessLogic
extension ColorSceneInteractor: ColorSceneBusinessLogic {

    func fetchData(request: ColorScene.Fetching.Request) {
        let color = worker.fetchColor(by: colorID)
        let response = ColorScene.Fetching.Response(color: color)
        presenter?.presentFetchingResult(response: response)
    }
}
