//
//  ColorSceneBuilder.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorSceneBuilder {
    
    static func build(colorID: ColorID) -> ColorSceneViewController {
        let viewController = configureModule(colorID: colorID)
        viewController.title = "Color Scene"
        return viewController
    }
    
    private static func configureModule(colorID: ColorID) -> ColorSceneViewController {
        let viewController = ColorSceneViewController()
        let interactor = ColorSceneInteractor(colorID: colorID)
        let presenter = ColorScenePresenter()
        let router = ColorSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        return viewController
    }
    
}
