//
//  ColorSceneModels.swift
//  Colors
//
//  Created by Alexander Vorobyev on 28/08/2019.
//  Copyright (c) 2019 Utkonos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorScene {
    
    struct DisplayedColor {
        var title: String
        var color: UIColor?
    }
    
    // MARK: Use cases
    
    enum Fetching {
        struct Request {
        }
        struct Response {
            var color: Color?
        }
        struct ViewModel {
            var displayedColor: DisplayedColor
        }
    }
}
